apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pullrequest
spec:
  serviceAccountName: tekton-bot
  pipelineSpec:
    params:
    - description: git url to clone
      name: REPO_URL
      type: string
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: PULL_PULL_SHA
      type: string
    tasks:
    - name: clone-build-test
      params:
      - name: REPO_URL
        value: $(params.REPO_URL)
      - name: PULL_PULL_SHA
        value: $(params.PULL_PULL_SHA)
      taskSpec:
        params:
        - description: git url to clone
          name: REPO_URL
          type: string
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: PULL_PULL_SHA
          type: string
        stepTemplate:
          name: ""
          volumeMounts:
          - name: workspace
            mountPath: /workspace
        steps:
        - name: git-clone
          image: alpine/git:v2.30.0
          command:
          - /bin/sh
          args:
          - -ce
          - |
            mkdir -p $HOME;
            git config --global --add user.name dippynark-bot;
            git config --global --add user.email lukeaddison785@gmail.com;
            git config --global credential.helper store;
            git clone $(inputs.params.REPO_URL) .;
            echo Cloned url: $(inputs.params.REPO_URL) to dir: `pwd`;
            git merge $(inputs.params.PULL_PULL_SHA);
            echo Merged PULL_PULL_SHA into master: $(inputs.params.PULL_PULL_SHA) to dir: `pwd`
          workingDir: /workspace
        - name: kaniko-build-push
          image: gcr.io/kaniko-project/executor:v1.6.0
          args:
          - --dockerfile=Dockerfile
          - --context=dir:///workspace
          - --destination=dippynark/goldengoose:$(inputs.params.PULL_PULL_SHA)
          volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker
        volumes:
        - name: workspace
          emptyDir: {}
        - name: kaniko-secret
          secret:
            secretName: tekton-container-registry-auth
            items:
            - key: .dockerconfigjson
              path: config.json
